export const SET_POPULAR_FILMS = 'SET_POPULAR_FILMS';
export const SET_POPULAR_FILMS_LAST_YEAR = 'SET_POPULAR_FILMS_LAST_YEAR';
export const SET_RELEASED_FILMS = 'SET_RELEASED_FILMS';
export const CHANGE_COUNT = 'CHANGE_COUNT';
export const SET_SEARCH_FILMS = 'SET_SEARCH_FILMS';
