export const SET_POPULAR_FILMS = 'SET_POPULAR_FILMS';
export const SET_PREMIERES = 'SET_PREMIERES';
export const SET_SEARCH_FILMS = 'SET_SEARCH_FILMS';
export const SET_TOP_FILMS = 'SET_TOP_FILMS';

export const SET_POPULAR_FRONT_FILMS = 'SET_POPULAR_FRONT_FILMS';
export const SET_FRONT_PREMIERES = 'SET_FRONT_PREMIERES';
export const SET_SEARCH_FRONT_FILMS = 'SET_SEARCH_FRONT_FILMS';
export const SET_TOP_FRONT_FILMS = 'SET_TOP_FRONT_FILMS';

export const SET_PAGINATION = 'SET_PAGINATION';

export const SET_FILTERS_YEARS = 'SET_FILTERS_YEARS';
export const SET_FILTERS_RATINGS = 'SET_FILTERS_RATINGS';
export const SET_FILTERS_ORDER = 'SET_FILTERS_ORDER';
export const SET_FILTERS_GENRE = 'SET_FILTERS_GENRE';
export const FILTERS_RESET = 'FILTERS_RESET';

export const SET_GENRES = 'SET_GENRES';
