export const SET_FILMS = 'SET_FILMS';

export const SET_POPULAR_FILMS = 'SET_POPULAR_FILMS';
export const SET_NEW_FILMS = 'SET_NEW_FILMS';
export const SET_SEARCH_FILMS = 'SET_SEARCH_FILMS';
export const SET_TOP_FILMS = 'SET_TOP_FILMS';

export const SET_POPULAR_FRONT_FILMS = 'SET_POPULAR_FRONT_FILMS';
export const SET_NEW_FRONT_FILMS = 'SET_NEW_FRONT_FILMS';
export const SET_SEARCH_FRONT_FILMS = 'SET_SEARCH_FRONT_FILMS';
export const SET_TOP_FRONT_FILMS = 'SET_TOP_FRONT_FILMS';

export const SET_PAGINATION = 'SET_PAGINATION';

export const SET_POPULAR_PAGES = 'SET_POPULAR_PAGES';
export const SET_NEW_PAGES = 'SET_NEW_PAGES';
export const SET_SEARCH_PAGES = 'SET_SEARCH_PAGES';
export const SET_TOP_PAGES = 'SET_TOP_PAGES';

export const SET_FILTERS_YEARS = 'SET_FILTERS_YEARS';
export const SET_FILTERS_RATINGS = 'SET_FILTERS_RATINGS';
export const SET_FILTERS_ORDER = 'SET_FILTERS_ORDER';
export const SET_FILTERS_GENRE = 'SET_FILTERS_GENRE';
export const FILTERS_RESET = 'FILTERS_RESET';

export const SET_GENRES = 'SET_GENRES';

export const TOGGLE_SEARCH_IS_FETCHING = 'TOGGLE_SEARCH_IS_FETCHING';
export const TOGGLE_NEW_IS_FETCHING = 'TOGGLE_NEW_IS_FETCHING';
export const TOGGLE_POPULAR_IS_FETCHING = 'TOGGLE_POPULAR_IS_FETCHING';
export const TOGGLE_TOP_IS_FETCHING = 'TOGGLE_TOP_IS_FETCHING';
